version: '3.1'
services:
  db:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
  # TODO
  #  app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app
  #   ports:
  #     - '4001:4001'
  #   depends_on:
  #     - db
  #   networks:
  #     - my_network
  #   env_file:
  #     - .env

# networks:
#   my_network:
#     driver: bridge
