version: '3.1'
services:
  db:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
# backend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: my-backend
#     depends_on:
#       - postgres
#     ports:
#       - "3000:3000"
# volumes:
#   postgres_data:
# services:
#   db:
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: example
#     ports:
#       - '5432:5432'
#     networks:
#       - my_network

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app
  #   ports:
  #     - '4001:4001'
  #   depends_on:
  #     - db
  #   networks:
  #     - my_network
  #   env_file:
  #     - .env

# networks:
#   my_network:
#     driver: bridge
