version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '5432:5432'
    networks:
      - my_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '4000:4000'
    depends_on:
      - db
    networks:
      - my_network
    env_file:
      -.env

networks:
  my_network:
    driver: bridge
